"""
Configuration Generator for lcd4linux
Generates lcd4linux.conf from the project configuration
"""

from typing import Dict, Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ..models import ProjectConfig

class ConfigGenerator:
    def __init__(self):
        self.indent_level = 0

    def generate(self, project: 'ProjectConfig', widgets: Dict[str, Any]) -> str:
        lines = []
        lines.append("# LCD4Linux Configuration")
        lines.append(f"# Generated by LCD4Linux Visual Editor")
        lines.append("")

        lines.extend(self._generate_display(project.display))
        lines.append("")

        lines.extend(self._generate_widgets(widgets))
        lines.append("")

        lines.extend(self._generate_layouts(project, widgets))
        lines.append("")

        lines.extend(self._generate_variables(project.variables))
        lines.append("")

        lines.append(f"Display '{project.display.name}'")
        if project.layouts:
            lines.append(f"Layout '{project.active_layout}'")

        return "\n".join(lines)

    def _generate_display(self, display) -> list:
        lines = []
        lines.append(f"Display {display.name} {{")
        self.indent_level += 1

        lines.append(f"{' ' * self.indent_level}Driver '{display.driver}'")
        
        if display.port:
            lines.append(f"{' ' * self.indent_level}Port '{display.port}'")
        
        if display.font:
            lines.append(f"{' ' * self.indent_level}Font '{display.font}'")
        
        if hasattr(display, 'font_size') and display.font_size:
            lines.append(f"{' ' * self.indent_level}FontSize '{display.font_size}'")
        
        if display.driver == "VNC":
            if hasattr(display, 'vnc_port') and display.vnc_port:
                lines.append(f"{' ' * self.indent_level}Port '{display.vnc_port}'")
        
        if display.driver == "X11":
            if hasattr(display, 'x11_display') and display.x11_display:
                lines.append(f"{' ' * self.indent_level}Display '{display.x11_display}'")
        
        lines.append(f"{' ' * self.indent_level}Xres '{display.width}'")
        lines.append(f"{' ' * self.indent_level}Yres '{display.height}'")
        
        if hasattr(display, 'bpp') and display.bpp:
            lines.append(f"{' ' * self.indent_level}Bpp '{display.bpp}'")
        
        lines.append(f"{' ' * self.indent_level}Orientation {display.orientation}")
        
        if display.driver in ["DPF", "HD44780", "SamsungSPF"]:
            lines.append(f"{' ' * self.indent_level}Backlight {display.backlight}")
        
        lines.append(f"{' ' * self.indent_level}Foreground '{display.foreground}'")
        lines.append(f"{' ' * self.indent_level}Background '{display.background}'")
        
        if hasattr(display, 'basecolor') and display.basecolor:
            lines.append(f"{' ' * self.indent_level}Basecolor '{display.basecolor}'")

        self.indent_level -= 1
        lines.append("}")

        return lines

    def _generate_widgets(self, widgets: Dict[str, Any]) -> list:
        lines = []

        for name, widget in widgets.items():
            widget_lines = self._generate_widget(name, widget)
            lines.extend(widget_lines)

        return lines

    def _generate_widget(self, name: str, widget) -> list:
        lines = []
        widget_type = widget.__class__.__name__.replace("WidgetConfig", "").lower()

        lines.append(f"Widget {name} {{")

        if widget_type == "text":
            lines.extend(self._generate_text_widget(widget))
        elif widget_type == "bar":
            lines.extend(self._generate_bar_widget(widget))
        elif widget_type == "image":
            lines.extend(self._generate_image_widget(widget))
        elif widget_type == "timer":
            lines.extend(self._generate_timer_widget(widget))
        elif widget_type == "icon":
            lines.extend(self._generate_icon_widget(widget))
        elif widget_type == "graph":
            lines.extend(self._generate_graph_widget(widget))
        elif widget_type == "arc":
            lines.extend(self._generate_arc_widget(widget))

        lines.append("}")

        return lines

    def _generate_text_widget(self, widget) -> list:
        lines = []
        indent = "    "

        lines.append(f"{indent}class 'Text'")

        if widget.expression:
            lines.append(f"{indent}expression {widget.expression}")

        if widget.prefix:
            lines.append(f"{indent}prefix '{widget.prefix}'")

        if widget.postfix:
            lines.append(f"{indent}postfix '{widget.postfix}'")

        lines.append(f"{indent}width {widget.width}")

        if widget.precision != 0:
            lines.append(f"{indent}precision {widget.precision}")

        lines.append(f"{indent}align '{widget.align}'")

        if widget.style:
            lines.append(f"{indent}style '{widget.style}'")

        if widget.foreground != "000000":
            lines.append(f"{indent}foreground '{widget.foreground}'")

        if widget.background != "ffffff":
            lines.append(f"{indent}background '{widget.background}'")

        if widget.update != 1000:
            lines.append(f"{indent}update {widget.update}")

        return lines

    def _generate_bar_widget(self, widget) -> list:
        lines = []
        indent = "    "

        lines.append(f"{indent}class 'Bar'")

        if widget.expression:
            lines.append(f"{indent}expression {widget.expression}")

        if widget.expression2:
            lines.append(f"{indent}expression2 {widget.expression2}")

        lines.append(f"{indent}length {widget.length}")

        if widget.min_val != 0:
            lines.append(f"{indent}min {widget.min_val}")

        if widget.max_val != 100:
            lines.append(f"{indent}max {widget.max_val}")

        lines.append(f"{indent}direction '{widget.direction}'")

        if widget.style:
            lines.append(f"{indent}style '{widget.style}'")

        if widget.foreground != "000000":
            lines.append(f"{indent}foreground '{widget.foreground}'")

        if widget.background != "ffffff":
            lines.append(f"{indent}background '{widget.background}'")

        if widget.update != 1000:
            lines.append(f"{indent}update {widget.update}")

        if widget.barcolor0 != "ff0000":
            lines.append(f"{indent}BarColor0 '{widget.barcolor0}'")

        if widget.barcolor1 != "00ff00":
            lines.append(f"{indent}BarColor1 '{widget.barcolor1}'")

        return lines

    def _generate_image_widget(self, widget) -> list:
        lines = []
        indent = "    "

        lines.append(f"{indent}class 'Image'")

        if widget.file:
            lines.append(f"{indent}file '{widget.file}'")

        lines.append(f"{indent}update {widget.update}")

        if widget.reload != 0:
            lines.append(f"{indent}reload {widget.reload}")

        if widget.visible != 1:
            lines.append(f"{indent}visible {widget.visible}")

        if widget.inverted != 0:
            lines.append(f"{indent}inverted {widget.inverted}")

        return lines

    def _generate_timer_widget(self, widget) -> list:
        lines = []
        indent = "    "

        lines.append(f"{indent}class 'Timer'")

        if widget.expression:
            lines.append(f"{indent}expression {widget.expression}")

        if widget.format != "%H:%M:%S":
            lines.append(f"{indent}format '{widget.format}'")

        lines.append(f"{indent}update {widget.update}")

        if widget.visible != 1:
            lines.append(f"{indent}visible {widget.visible}")

        return lines

    def _generate_icon_widget(self, widget) -> list:
        lines = []
        indent = "    "

        lines.append(f"{indent}class 'Icon'")

        if widget.icon:
            lines.append(f"{indent}icon '{widget.icon}'")

        if widget.expression:
            lines.append(f"{indent}expression {widget.expression}")

        lines.append(f"{indent}update {widget.update}")

        if widget.visible != 1:
            lines.append(f"{indent}visible {widget.visible}")

        return lines

    def _generate_graph_widget(self, widget) -> list:
        lines = []
        indent = "    "

        lines.append(f"{indent}class 'Graph'")

        if widget.expression:
            lines.append(f"{indent}expression {widget.expression}")

        lines.append(f"{indent}width {widget.width}")
        lines.append(f"{indent}height {widget.height}")

        if widget.min_val != 0:
            lines.append(f"{indent}min {widget.min_val}")

        if widget.max_val != 100:
            lines.append(f"{indent}max {widget.max_val}")

        lines.append(f"{indent}update {widget.update}")

        if widget.points != 50:
            lines.append(f"{indent}points {widget.points}")

        if widget.style != 0:
            lines.append(f"{indent}style {widget.style}")

        if widget.color != "00FF00":
            lines.append(f"{indent}color '{widget.color}'")

        if widget.fill != "003300":
            lines.append(f"{indent}fill '{widget.fill}'")

        if widget.bg != "000000":
            lines.append(f"{indent}bg '{widget.bg}'")

        if widget.grid != "404040":
            lines.append(f"{indent}grid '{widget.grid}'")

        return lines

    def _generate_arc_widget(self, widget) -> list:
        lines = []
        indent = "    "

        lines.append(f"{indent}class 'Arc'")

        if widget.expression:
            lines.append(f"{indent}expression {widget.expression}")

        lines.append(f"{indent}width {widget.width}")
        lines.append(f"{indent}height {widget.height}")

        if widget.min_val != 0:
            lines.append(f"{indent}min {widget.min_val}")

        if widget.max_val != 100:
            lines.append(f"{indent}max {widget.max_val}")

        lines.append(f"{indent}update {widget.update}")

        if widget.style != "semi":
            lines.append(f"{indent}style '{widget.style}'")

        if widget.ticks != 5:
            lines.append(f"{indent}ticks {widget.ticks}")

        if widget.minor != 5:
            lines.append(f"{indent}minor {widget.minor}")

        if widget.thickness != 8:
            lines.append(f"{indent}thickness {widget.thickness}")

        if widget.arc != "404040":
            lines.append(f"{indent}arc '{widget.arc}'")

        if widget.needle != "FF0000":
            lines.append(f"{indent}needle '{widget.needle}'")

        if widget.center != "808080":
            lines.append(f"{indent}center '{widget.center}'")

        if widget.bg != "000000":
            lines.append(f"{indent}bg '{widget.bg}'")

        return lines

    def _generate_layouts(self, project: 'ProjectConfig', widgets: Dict[str, Any]) -> list:
        lines = []

        for layout in project.layouts:
            lines.append(f"Layout {layout.name} {{")

            rows = {}
            for p in layout.placements:
                row = p.position.y // 20
                col = p.position.x // 10

                if row not in rows:
                    rows[row] = []

                rows[row].append((col, p.widget_name))

            for row_num in sorted(rows.keys()):
                items = sorted(rows[row_num], key=lambda x: x[0])
                row_name = f"Row{row_num + 1}"

                line = f"    {row_name} {{ "
                col_parts = []
                for col, widget_name in items:
                    col_parts.append(f"Col{col + 1} '{widget_name}'")
                line += " | ".join(col_parts)
                line += " }"
                lines.append(line)

            lines.append("}")
            lines.append("")

        return lines

    def _generate_variables(self, variables) -> list:
        lines = []

        if variables.tick != 500 or variables.custom_vars:
            lines.append("Variables {")
            lines.append(f"    tick {variables.tick}")

            for name, value in variables.custom_vars.items():
                lines.append(f"    {name} {value}")

            lines.append("}")
            lines.append("")

        return lines
